# Generated by Django 4.2 on 2026-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
    ]
