# Generated by Django 3.2.25 on 2026-03-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20260313_1343'),
        ('shops', '0005_remove_shop_latitude_remove_shop_longitude'),
    ]

    operations = [
    ]
